#version: '3.8'
#
#services:
#  web:
#    build: .
#    ports:
#      - "8000:8000"
#    env_file: .env
#    depends_on:
#      - db
#    volumes:
#      - .:/app
#
#  db:
#    image: postgres:15
#    env_file: .env
#    ports:
#      - "5433:5432" # primary
##      - "5433:5432" # secondary - if in system already using postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    command: >
#      postgres
#      -c shared_preload_libraries=pg_stat_statements
#      -c pg_stat_statements.track=all
#
#volumes:
#  postgres_data: